### ISSUE TITLE
[Bug]: Readme başlık düzeltilmemiş.

### ISSUE THREAD

**Issue by menoktaokan** [acildeprem/api#3]
### Sorun açıklaması

Readme başlık düzeltilmemiş, kopyalanan içerik kalmış.

### Satır sayısı

1

### Ne olması gerekiyordu?

Readme başlık düzeltilmemiş.

### Platform

Database (Default)

### Yukarıdaki adımları takip ettiniz mi?

- [X] Evet, eminim.

**Comment by productdevbook** [comment]
Tamam ben onu duzenleyeyim hemen
